import { Card } from '@/types/card';

export const cards: Card[] = [
  {
    id: "scholarship-program-2023",
    title: "Scholarship Program",
    description: "Empowering futures through education",
    longDescription: "Our comprehensive scholarship program aims to break barriers in education by providing financial support, mentorship, and resources to talented students from underprivileged backgrounds. We cover tuition, books, and living expenses to ensure students can focus on their studies and achieve their full potential.",
    imageUrl: "https://ipsd.ps/uc_files/image/fit/150/150/app_files/new_project_2022_12_20t115410725png_167152995998331987598067.png?vsig=9cd6c82e1478481152e94579b3b7d108",
    category: "education",
    ctaText: "Apply Now",
    ctaLink: "https://example.com/scholarship-application",
  },
  {
    id: "healthcare-initiative-2023",
    title: "Community Health Initiative",
    description: "Bringing quality healthcare to underserved areas",
    longDescription: "Our Community Health Initiative is dedicated to improving access to essential medical services in underserved areas. We provide mobile clinics, telemedicine services, and health education programs to ensure that everyone has access to quality healthcare, regardless of their location or economic status.",
    imageUrl: "https://ipsd.ps/uc_files/image/fit/150/150/app_files/new_project_2022_12_20t113356653png_167152874638741355299024.png?vsig=a16133da22f5be0a0f52c94bfe982c2a",
    category: "healthcare",
    ctaText: "Find a Clinic",
    ctaLink: "https://example.com/find-clinic",
  },
  {
    id: "vocational-training-2023",
    title: "Skills for Tomorrow",
    description: "Empowering individuals with in-demand skills",
    longDescription: "Our 'Skills for Tomorrow' program offers comprehensive vocational training in high-demand fields. From digital marketing to sustainable agriculture, we provide hands-on training, industry certifications, and job placement assistance to help individuals build rewarding careers and achieve economic independence.",
    imageUrl: "https://ipsd.ps/uc_files/image/fit/150/150/app_files/new_project_2022_12_20t114756399png_167152959555022069221605.png?vsig=c7f4ff09da2a1af2fec400ec902ce889",
    category: "training",
    ctaText: "Explore Courses",
    ctaLink: "https://example.com/vocational-courses",
  },
  {
    id: "community-development-2023",
    title: "Thriving Communities",
    description: "Building resilient and sustainable neighborhoods",
    longDescription: "Our 'Thriving Communities' initiative takes a holistic approach to community development. We implement programs addressing poverty, inequality, and social challenges through community centers, support services, and collaborative projects. Our goal is to create sustainable solutions and foster community resilience.",
    imageUrl: "https://ipsd.ps/uc_files/image/fit/150/150/app_files/new_project_2022_12_20t114355704png_167152937654061267020674.png?vsig=6926150cc33b4603bf0e7054c8257dd3",
    category: "welfare",
    ctaText: "Join Our Efforts",
    ctaLink: "https://example.com/community-volunteer",
  },
  {
    id: "tweet-tech-innovations-2023",
    title: "Tweet Tech Innovations",
    description: "Pioneering solutions for the digital age",
    longDescription: "Tweet Tech Innovations is at the forefront of digital transformation. We specialize in cutting-edge web technologies, cloud computing, and AI-driven solutions. Our team of experts works tirelessly to develop innovative products and services that help businesses thrive in the rapidly evolving digital landscape.",
    imageUrl: "https://ipsd.ps/uc_files/image/fit/150/150/app_files/new_project_2022_12_20t114927935png_167152967868961842553511.png?vsig=eaf0ea739172c87b5f26e499a701be84",
    category: "technology",
    ctaText: "Discover Our Solutions",
    ctaLink: "https://example.com/tweet-tech-solutions",
  },
  {
    id: "research-grants-2023",
    title: "Frontier Research Grants",
    description: "Fueling groundbreaking discoveries",
    longDescription: "Our Frontier Research Grants program supports innovative research across various disciplines. We provide funding for projects that push the boundaries of knowledge, from renewable energy technologies to breakthroughs in medical science. Our grants aim to accelerate scientific progress and address global challenges.",
    imageUrl: "https://ipsd.ps/uc_files/image/fit/150/150/app_files/new_project_2022_12_20t115248177png_16715298819726912928714.png?vsig=b4a7eeed70cb6371d25b72dad09c0a76",
    category: "education",
    ctaText: "Apply for a Grant",
    ctaLink: "https://example.com/research-grant-application",
  },
  {
    id: "smart-it-solutions-2023",
    title: "Smart IT Solutions",
    description: "Empowering businesses through technology",
    longDescription: "Smart IT Solutions is a leading provider of comprehensive IT services. We offer custom software development, advanced cybersecurity measures, and IT infrastructure management. Our team of experts is dedicated to helping organizations leverage technology to increase efficiency, security, and competitiveness in the digital marketplace.",
    imageUrl: "https://ipsd.ps/uc_files/image/fit/150/150/app_files/new_project_2022_12_20t114243335png_16715292832212991924760.png?vsig=f335bc1a992c737ca8972597c13ce066",
    category: "technology",
    ctaText: "Explore Our Services",
    ctaLink: "https://example.com/smart-it-services",
  },
];

